server:
  host: 0.0.0.0
  port: 8000

teleprompter:
  next_lines: 5   #需设置为实际数量+1

subtitle:
  remove_brackets: true

ndi:
  enable: true
  name: LiveCaptionNDI

hotkeys:
  next: ArrowDown
  prev: ArrowUp
  first: Home
  last: End